on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: xiao_ble
            shield: board24_2_l
            artifact_name: board24_2_l-xiao_ble-zmk
          - board: xiao_ble
            shield: board24_2_r
            artifact_name: board24_2_r-xiao_ble-zmk
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-west-${{ hashFiles('config/west.yml') }}
          restore-keys: ${{ runner.os }}-west-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update --fetch-opt=--filter=tree:0

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}"

      - name: Kconfig file
        if: always()
        run: if [ -f build/zephyr/.config ]; then grep -v -e "^#" -e "^$" build/zephyr/.config | sort; else echo "No output"; fi

      - name: DTS file
        if: always()
        run: if [ -f build/zephyr/zephyr.dts ]; then cat build/zephyr/zephyr.dts; else echo "No output"; fi

      - name: Rename artifacts
        run: mkdir -p artifacts && if [ -f build/zephyr/zmk.uf2 ]; then cp build/zephyr/zmk.uf2 artifacts/${{ matrix.artifact_name }}.uf2; elif [ -f build/zephyr/zmk.bin ]; then cp build/zephyr/zmk.bin artifacts/${{ matrix.artifact_name }}.bin; fi

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.artifact_name }}
          path: artifacts/

  merge:
    runs-on: ubuntu-latest
    needs: build
    name: Merge Output Artifacts
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: firmware
          pattern: firmware-*
          delete-merged: true